# Generated by Django 4.1.7 on 2023-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_alter_accounttype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
