# Generated by Django 4.1.7 on 2023-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_address_alter_user_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2023-03-04'),
            preserve_default=False,
        ),
    ]
