# Generated by Django 4.1.7 on 2023-03-09 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 13, 57, 5, 382205, tzinfo=datetime.timezone.utc)),
        ),
    ]
