# Generated by Django 4.1.7 on 2023-03-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDestinationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='transaction_destination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reference_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_fail', models.BooleanField(default=False)),
                ('transaction_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_user', to='bank.transactiondestinationuser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_type', to='bank.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
