# Generated by Django 4.1.7 on 2023-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionway',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
