# Generated by Django 4.1.7 on 2023-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_transactiontype_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='done_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
