# Generated by Django 4.1.7 on 2023-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_transaction_done_at_transaction_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
